# Generated by Django 3.2.7 on 2021-09-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yolopay',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('emotion', models.CharField(max_length=50)),
                ('yolo_fire', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
