# Generated by Django 3.2.5 on 2021-09-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yolopay',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
